/*
 * Standalone test for per-connection TLS (tls-conn.c).
 *
 * Validates:
 * 1. Global TLS context initialization (load certs once)
 * 2. Multiple parallel TLS connections (simulates P3 threads)
 * 3. Bidirectional data transfer over each connection
 * 4. Concurrent send/recv across threads (no global state corruption)
 * 5. Graceful shutdown of all connections
 *
 * Usage: ./test-tls-conn [num_threads]
 *   Default: 8 parallel connections (like CLONE P3 threads)
 *
 * Requires: test certs in ./certs/ (generated by gen-certs.sh)
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <pthread.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <errno.h>
#include <signal.h>
#include <sys/time.h>

#include <gnutls/gnutls.h>

/* ====== Inline tls-conn implementation for standalone test ====== */

#define pr_err(fmt, ...) fprintf(stderr, "[ERROR] " fmt, ##__VA_ARGS__)
#define pr_info(fmt, ...) fprintf(stdout, "[INFO]  " fmt, ##__VA_ARGS__)
#define pr_perror(msg) perror("[PERROR] " msg)

struct tls_conn {
	gnutls_session_t session;
	int socket_fd;
	int io_flags;
};

static struct {
	gnutls_certificate_credentials_t x509_cred;
	int initialized;
	pthread_mutex_t lock;
} g_tls_ctx = {
	.initialized = 0,
	.lock = PTHREAD_MUTEX_INITIALIZER,
};

static char *g_cacert = "certs/ca.crt";
static char *g_cert = "certs/server.crt";
static char *g_key = "certs/server.key";

static int tls_global_init(void)
{
	int ret = 0;

	pthread_mutex_lock(&g_tls_ctx.lock);
	if (g_tls_ctx.initialized)
		goto out;

	gnutls_global_init();

	ret = gnutls_certificate_allocate_credentials(&g_tls_ctx.x509_cred);
	if (ret != GNUTLS_E_SUCCESS) {
		pr_err("alloc creds: %s\n", gnutls_strerror(ret));
		ret = -1;
		goto out;
	}

	ret = gnutls_certificate_set_x509_trust_file(g_tls_ctx.x509_cred,
						     g_cacert,
						     GNUTLS_X509_FMT_PEM);
	if (ret <= 0) {
		pr_err("load CA cert failed (ret=%d): %s\n", ret, g_cacert);
		ret = -1;
		goto out;
	}

	ret = gnutls_certificate_set_x509_key_file(g_tls_ctx.x509_cred,
						   g_cert, g_key,
						   GNUTLS_X509_FMT_PEM);
	if (ret != GNUTLS_E_SUCCESS) {
		pr_err("load cert/key: %s\n", gnutls_strerror(ret));
		ret = -1;
		goto out;
	}

	g_tls_ctx.initialized = 1;
	ret = 0;
	pr_info("Global TLS context initialized\n");
out:
	pthread_mutex_unlock(&g_tls_ctx.lock);
	return ret;
}

static void tls_global_deinit(void)
{
	if (g_tls_ctx.initialized) {
		gnutls_certificate_free_credentials(g_tls_ctx.x509_cred);
		gnutls_global_deinit();
		g_tls_ctx.initialized = 0;
	}
}

static ssize_t _push_cb(gnutls_transport_ptr_t ptr,
			const void *data, size_t sz)
{
	struct tls_conn *conn = (struct tls_conn *)ptr;
	return send(conn->socket_fd, data, sz, conn->io_flags);
}

static ssize_t _pull_cb(gnutls_transport_ptr_t ptr,
			void *data, size_t sz)
{
	struct tls_conn *conn = (struct tls_conn *)ptr;
	return recv(conn->socket_fd, data, sz, conn->io_flags);
}

static struct tls_conn *tls_conn_new(int sockfd, int is_server)
{
	struct tls_conn *conn;
	unsigned int flags;
	int ret;

	if (!g_tls_ctx.initialized) {
		if (tls_global_init())
			return NULL;
	}

	conn = calloc(1, sizeof(*conn));
	if (!conn)
		return NULL;

	conn->socket_fd = sockfd;
	conn->io_flags = 0;

	flags = is_server ? GNUTLS_SERVER : GNUTLS_CLIENT;
	ret = gnutls_init(&conn->session, flags);
	if (ret != GNUTLS_E_SUCCESS) {
		pr_err("gnutls_init: %s\n", gnutls_strerror(ret));
		goto err_free;
	}

	ret = gnutls_credentials_set(conn->session, GNUTLS_CRD_CERTIFICATE,
				     g_tls_ctx.x509_cred);
	if (ret != GNUTLS_E_SUCCESS) {
		pr_err("cred_set: %s\n", gnutls_strerror(ret));
		goto err_session;
	}

	ret = gnutls_set_default_priority(conn->session);
	if (ret != GNUTLS_E_SUCCESS) {
		pr_err("priority: %s\n", gnutls_strerror(ret));
		goto err_session;
	}

	gnutls_transport_set_ptr(conn->session, conn);
	gnutls_transport_set_push_function(conn->session, _push_cb);
	gnutls_transport_set_pull_function(conn->session, _pull_cb);

	if (is_server) {
		gnutls_certificate_server_set_request(conn->session,
						      GNUTLS_CERT_REQUIRE);
		gnutls_certificate_send_x509_rdn_sequence(conn->session, 1);
	}

	do {
		ret = gnutls_handshake(conn->session);
	} while (ret == GNUTLS_E_AGAIN || ret == GNUTLS_E_INTERRUPTED);

	if (ret != GNUTLS_E_SUCCESS) {
		pr_err("handshake (fd=%d, %s): %s\n", sockfd,
		       is_server ? "server" : "client",
		       gnutls_strerror(ret));
		goto err_session;
	}

	return conn;

err_session:
	gnutls_deinit(conn->session);
err_free:
	free(conn);
	return NULL;
}

static void tls_conn_free(struct tls_conn *conn)
{
	if (!conn)
		return;
	gnutls_bye(conn->session, GNUTLS_SHUT_WR);
	gnutls_deinit(conn->session);
	free(conn);
}

static ssize_t tls_conn_send_all(struct tls_conn *conn, const void *buf,
				 size_t len, int flags)
{
	const char *cursor = buf;
	size_t remaining = len;

	while (remaining > 0) {
		ssize_t ret;

		conn->io_flags = flags;
		ret = gnutls_record_send(conn->session, cursor, remaining);
		conn->io_flags = 0;

		if (ret < 0) {
			if (ret == GNUTLS_E_AGAIN || ret == GNUTLS_E_INTERRUPTED)
				continue;
			pr_err("send_all: %s\n", gnutls_strerror(ret));
			return -1;
		}
		cursor += ret;
		remaining -= ret;
	}
	return len;
}

static ssize_t tls_conn_recv_all(struct tls_conn *conn, void *buf,
				 size_t len, int flags)
{
	char *cursor = buf;
	size_t remaining = len;

	while (remaining > 0) {
		ssize_t ret;

		conn->io_flags = flags;
		ret = gnutls_record_recv(conn->session, cursor, remaining);
		conn->io_flags = 0;

		if (ret < 0) {
			if (ret == GNUTLS_E_AGAIN || ret == GNUTLS_E_INTERRUPTED)
				continue;
			pr_err("recv_all: %s\n", gnutls_strerror(ret));
			return -1;
		}
		if (ret == 0)
			return len - remaining;

		cursor += ret;
		remaining -= ret;
	}
	return len;
}

/* ====== Test infrastructure ====== */

#define TEST_PORT_BASE	19500
#define DATA_SIZE	(256 * 1024)  /* 256KB - simulates one CLONE batch */
#define NUM_BATCHES	100           /* 100 batches per thread */

static int g_listen_sk = -1;
static int g_port = 0;
static volatile int g_server_ready = 0;
static volatile int g_tests_passed = 0;
static volatile int g_tests_failed = 0;

struct thread_result {
	int thread_id;
	int success;
	unsigned long bytes_transferred;
	double elapsed_ms;
};

/* Server thread: accepts one connection, receives data, echoes checksum back */
static void *server_thread(void *arg)
{
	int thread_id = *(int *)arg;
	struct sockaddr_in caddr;
	socklen_t clen = sizeof(caddr);
	int sk;
	struct tls_conn *conn;
	char *buf;
	unsigned long total_bytes = 0;
	int batch;
	struct timeval t_start, t_end;

	sk = accept(g_listen_sk, (struct sockaddr *)&caddr, &clen);
	if (sk < 0) {
		pr_perror("server accept");
		return NULL;
	}

	gettimeofday(&t_start, NULL);

	conn = tls_conn_new(sk, 1);
	if (!conn) {
		pr_err("server[%d]: TLS handshake failed\n", thread_id);
		close(sk);
		return NULL;
	}

	buf = malloc(DATA_SIZE);
	if (!buf) {
		tls_conn_free(conn);
		close(sk);
		return NULL;
	}

	/* Receive NUM_BATCHES batches, compute checksum, send back */
	for (batch = 0; batch < NUM_BATCHES; batch++) {
		unsigned long checksum = 0;
		ssize_t ret;
		int i;

		ret = tls_conn_recv_all(conn, buf, DATA_SIZE, 0);
		if (ret != DATA_SIZE) {
			pr_err("server[%d]: short recv batch %d (got %zd)\n",
			       thread_id, batch, ret);
			break;
		}
		total_bytes += ret;

		/* Compute simple checksum */
		for (i = 0; i < DATA_SIZE; i++)
			checksum += (unsigned char)buf[i];

		/* Send checksum back */
		ret = tls_conn_send_all(conn, &checksum, sizeof(checksum), 0);
		if (ret != sizeof(checksum)) {
			pr_err("server[%d]: failed to send checksum\n", thread_id);
			break;
		}
	}

	gettimeofday(&t_end, NULL);

	free(buf);
	tls_conn_free(conn);
	close(sk);

	double elapsed = (t_end.tv_sec - t_start.tv_sec) * 1000.0 +
			 (t_end.tv_usec - t_start.tv_usec) / 1000.0;

	struct thread_result *res = malloc(sizeof(*res));
	res->thread_id = thread_id;
	res->success = (batch == NUM_BATCHES);
	res->bytes_transferred = total_bytes;
	res->elapsed_ms = elapsed;
	return res;
}

/* Client thread: connects, sends data, verifies checksums */
static void *client_thread(void *arg)
{
	int thread_id = *(int *)arg;
	int sk;
	struct sockaddr_in addr;
	struct tls_conn *conn;
	char *buf;
	unsigned long total_bytes = 0;
	int batch;
	struct timeval t_start, t_end;

	sk = socket(AF_INET, SOCK_STREAM, 0);
	if (sk < 0) {
		pr_perror("client socket");
		return NULL;
	}

	memset(&addr, 0, sizeof(addr));
	addr.sin_family = AF_INET;
	addr.sin_port = htons(g_port);
	addr.sin_addr.s_addr = htonl(INADDR_LOOPBACK);

	if (connect(sk, (struct sockaddr *)&addr, sizeof(addr)) < 0) {
		pr_perror("client connect");
		close(sk);
		return NULL;
	}

	gettimeofday(&t_start, NULL);

	conn = tls_conn_new(sk, 0);
	if (!conn) {
		pr_err("client[%d]: TLS handshake failed\n", thread_id);
		close(sk);
		return NULL;
	}

	buf = malloc(DATA_SIZE);
	if (!buf) {
		tls_conn_free(conn);
		close(sk);
		return NULL;
	}

	/* Fill buffer with pattern based on thread_id */
	for (int i = 0; i < DATA_SIZE; i++)
		buf[i] = (char)((thread_id * 37 + i) & 0xFF);

	/* Compute expected checksum */
	unsigned long expected_checksum = 0;
	for (int i = 0; i < DATA_SIZE; i++)
		expected_checksum += (unsigned char)buf[i];

	int verified_ok = 1;

	for (batch = 0; batch < NUM_BATCHES; batch++) {
		unsigned long server_checksum;
		ssize_t ret;

		ret = tls_conn_send_all(conn, buf, DATA_SIZE, 0);
		if (ret != DATA_SIZE) {
			pr_err("client[%d]: short send batch %d\n",
			       thread_id, batch);
			break;
		}
		total_bytes += ret;

		/* Receive and verify checksum */
		ret = tls_conn_recv_all(conn, &server_checksum,
					sizeof(server_checksum), 0);
		if (ret != sizeof(server_checksum)) {
			pr_err("client[%d]: failed to recv checksum\n", thread_id);
			break;
		}

		if (server_checksum != expected_checksum) {
			pr_err("client[%d]: CHECKSUM MISMATCH batch %d "
			       "(got %lu, expected %lu)\n",
			       thread_id, batch,
			       server_checksum, expected_checksum);
			verified_ok = 0;
			break;
		}
	}

	gettimeofday(&t_end, NULL);

	free(buf);
	tls_conn_free(conn);
	close(sk);

	double elapsed = (t_end.tv_sec - t_start.tv_sec) * 1000.0 +
			 (t_end.tv_usec - t_start.tv_usec) / 1000.0;

	struct thread_result *res = malloc(sizeof(*res));
	res->thread_id = thread_id;
	res->success = (batch == NUM_BATCHES && verified_ok);
	res->bytes_transferred = total_bytes;
	res->elapsed_ms = elapsed;
	return res;
}

static int setup_listen_socket(void)
{
	struct sockaddr_in addr;
	int sk, opt = 1;

	sk = socket(AF_INET, SOCK_STREAM, 0);
	if (sk < 0) {
		pr_perror("socket");
		return -1;
	}

	setsockopt(sk, SOL_SOCKET, SO_REUSEADDR, &opt, sizeof(opt));

	memset(&addr, 0, sizeof(addr));
	addr.sin_family = AF_INET;
	addr.sin_addr.s_addr = htonl(INADDR_LOOPBACK);
	addr.sin_port = 0; /* Let kernel pick */

	if (bind(sk, (struct sockaddr *)&addr, sizeof(addr)) < 0) {
		pr_perror("bind");
		close(sk);
		return -1;
	}

	socklen_t alen = sizeof(addr);
	getsockname(sk, (struct sockaddr *)&addr, &alen);
	g_port = ntohs(addr.sin_port);

	if (listen(sk, 128) < 0) {
		pr_perror("listen");
		close(sk);
		return -1;
	}

	return sk;
}

int main(int argc, char **argv)
{
	int num_threads = 8;
	int i;
	pthread_t *server_threads, *client_threads;
	int *thread_ids;
	struct timeval t_start, t_end;
	unsigned long total_bytes = 0;
	int all_passed = 1;

	if (argc > 1)
		num_threads = atoi(argv[1]);
	if (num_threads < 1 || num_threads > 64)
		num_threads = 8;

	signal(SIGPIPE, SIG_IGN);

	printf("=== TLS Per-Connection Test ===\n");
	printf("Threads: %d\n", num_threads);
	printf("Data per batch: %d KB\n", DATA_SIZE / 1024);
	printf("Batches per thread: %d\n", NUM_BATCHES);
	printf("Total data: %lu MB\n",
	       (unsigned long)num_threads * NUM_BATCHES * DATA_SIZE / (1024 * 1024));
	printf("\n");

	/* Initialize global TLS context */
	if (tls_global_init()) {
		pr_err("Failed to initialize TLS\n");
		return 1;
	}

	/* Setup listen socket */
	g_listen_sk = setup_listen_socket();
	if (g_listen_sk < 0)
		return 1;

	printf("Listening on port %d\n\n", g_port);

	/* Allocate thread arrays */
	server_threads = calloc(num_threads, sizeof(pthread_t));
	client_threads = calloc(num_threads, sizeof(pthread_t));
	thread_ids = calloc(num_threads, sizeof(int));

	gettimeofday(&t_start, NULL);

	/* Start server threads (one per expected connection) */
	for (i = 0; i < num_threads; i++) {
		thread_ids[i] = i;
		pthread_create(&server_threads[i], NULL,
			       server_thread, &thread_ids[i]);
	}

	/* Small delay to ensure servers are in accept() */
	usleep(10000);

	/* Start client threads (parallel connections) */
	for (i = 0; i < num_threads; i++) {
		pthread_create(&client_threads[i], NULL,
			       client_thread, &thread_ids[i]);
	}

	/* Wait for all clients */
	printf("--- Client Results ---\n");
	for (i = 0; i < num_threads; i++) {
		struct thread_result *res;
		pthread_join(client_threads[i], (void **)&res);
		if (res) {
			double mbps = res->bytes_transferred /
				      (res->elapsed_ms / 1000.0) / (1024 * 1024);
			printf("  client[%d]: %s  %lu KB in %.1f ms (%.1f MB/s)\n",
			       res->thread_id,
			       res->success ? "PASS" : "FAIL",
			       res->bytes_transferred / 1024,
			       res->elapsed_ms, mbps);
			total_bytes += res->bytes_transferred;
			if (!res->success)
				all_passed = 0;
			free(res);
		} else {
			printf("  client[%d]: FAIL (no result)\n", i);
			all_passed = 0;
		}
	}

	/* Wait for all servers */
	printf("\n--- Server Results ---\n");
	for (i = 0; i < num_threads; i++) {
		struct thread_result *res;
		pthread_join(server_threads[i], (void **)&res);
		if (res) {
			printf("  server[%d]: %s  %lu KB\n",
			       res->thread_id,
			       res->success ? "PASS" : "FAIL",
			       res->bytes_transferred / 1024);
			if (!res->success)
				all_passed = 0;
			free(res);
		} else {
			printf("  server[%d]: FAIL (no result)\n", i);
			all_passed = 0;
		}
	}

	gettimeofday(&t_end, NULL);

	double total_elapsed = (t_end.tv_sec - t_start.tv_sec) * 1000.0 +
			       (t_end.tv_usec - t_start.tv_usec) / 1000.0;
	double total_mbps = total_bytes / (total_elapsed / 1000.0) / (1024 * 1024);

	printf("\n=== Summary ===\n");
	printf("Total: %lu MB transferred in %.1f ms\n",
	       total_bytes / (1024 * 1024), total_elapsed);
	printf("Aggregate throughput: %.1f MB/s\n", total_mbps);
	printf("Result: %s\n\n", all_passed ? "ALL PASSED" : "SOME FAILED");

	/* Cleanup */
	close(g_listen_sk);
	free(server_threads);
	free(client_threads);
	free(thread_ids);
	tls_global_deinit();

	return all_passed ? 0 : 1;
}
